### ISSUE TITLE
additional claim

### ISSUE THREAD

**Issue by yusef-ho** [FirebaseExtended/custom-auth-samples#19]
Hello, 
while i was reading this article "[Authenticate your Firebase users with LINE Login](https://firebase.googleblog.com/2016/11/authenticate-your-firebase-users-with-line-login.html)"
There is additionalClaims in server.js, but i didn't see where we put this code?
Thanks

**Comment by samtstern** [comment]
@yusef-ho that's a good catch!  The custom claims should be the second argument.

```js
function generateFirebaseToken(lineMid) {
  var firebaseUid = 'line:' + lineMid;
  var additionalClaims = {
    provider: 'LINE'
  };
  return firebase.auth().createCustomToken(firebaseUid, additionalClaims);
}
```

More information here:
https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk

**Comment by samtstern** [comment]
cc @khanhlvg
